language: c
install: true
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
	    - llvm-toolchain-precise-3.6
          packages:
            - gcc-4.9
	    - clang-3.6
      env: COMPILER=gcc-4.9
      script:
        - make tests
	- ./bin/test0a
  	- ./bin/test0b
  	- ./bin/test0c
  	- make clean
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
	    - llvm-toolchain-precise-3.6
          packages:
            - gcc-5
	    - clang-3.6
      env: COMPILER=gcc-5
      script:
        - make tests
	- ./bin/test0a
  	- ./bin/test0b
  	- ./bin/test0c
  	- make clean
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang-3.6
      script:
        - make tests
	- ./bin/test0a
  	- ./bin/test0b
  	- ./bin/test0c
  	- make clean
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang-3.7
      script:
        - make tests
	- ./bin/test0a
  	- ./bin/test0b
  	- ./bin/test0c
  	- make clean