language: c
install: true
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - gcc-4.9
            - clang-3.6
      env: COMPILER=gcc-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - gcc-5
            - clang-3.6
      env: COMPILER=gcc-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang-3.7
script:
  - cp /usr/local/clang-3.4/lib/libclang.so /usr/local/lib/
  - cp /usr/local/clang-3.4/lib/libclang.so /usr/local/lib64/
  - ld --verbose
  - make tests
  - ./bin/test0a
  - ./bin/test0b
  - ./bin/test0c
  - make clean